import api from './client';

export function getVerificationStatus() {
  return api.get('/verification');
}

export function getVerificationHistory() {
  return api.get('/verification/history');
}

export function submitVerification({ document_number, document_expiry, documentImage, selfieImage }) {
  const form = new FormData();
  form.append('document_number', document_number);
  form.append('document_expiry', document_expiry);
  form.append('document_image', documentImage);
  form.append('selfie_image', selfieImage);

  // Don't set Content-Type manually — the multipart boundary has to be
  // generated by whatever is actually encoding the body (the browser's
  // XHR on web, native networking on iOS/Android). A hardcoded
  // 'multipart/form-data' with no boundary produces a body the server
  // can't parse, so every field (including the image) arrives empty.
  return api.post('/verification', form);
}

export function getVirtualCard() {
  return api.get('/virtual-card');
}
